// Etichette italiane del vocabolario metriche TEAM-1. Vivono qui, lato presentazione:
// i contratti restano neutri e la UI non dipende da naming del provider.
import type {
  PlayerMetricKey,
  SquadPosition,
  TeamMetricGroup,
  TeamMetricKey,
} from "@iqstats/shared";

export const TEAM_GROUP_LABELS: Readonly<Record<TeamMetricGroup, string>> = {
  shooting: "Tiro",
  possession: "Possesso e costruzione",
  defence: "Difesa",
  goalkeeping: "Portiere",
  discipline: "Disciplina e palle inattive",
};

export const TEAM_METRIC_LABELS: Readonly<Record<TeamMetricKey, string>> = {
  shots: "Tiri",
  shotsOnTarget: "Tiri in porta",
  fouls: "Falli commessi",
  corners: "Corner",
  yellowCards: "Cartellini gialli",
  goalkeeperSaves: "Parate",
  offsides: "Fuorigioco",

  shotsInsideBox: "Tiri in area",
  shotsOutsideBox: "Tiri da fuori area",
  shotsOffTarget: "Tiri fuori misura",
  blockedShots: "Tiri respinti",
  hitWoodwork: "Legni colpiti",
  bigChances: "Grandi occasioni",
  bigChancesScored: "Grandi occasioni segnate",
  bigChancesMissed: "Grandi occasioni fallite",
  expectedGoals: "Gol attesi (xG)",
  xgActual: "xG, seconda misura della fonte",
  touchesInPenaltyArea: "Tocchi in area avversaria",

  ballPossession: "Possesso palla",
  passes: "Passaggi tentati",
  accuratePasses: "Passaggi riusciti",
  passAccuracy: "Precisione dei passaggi",
  longBallsAttempted: "Lanci lunghi tentati",
  longBallsAccuracy: "Precisione dei lanci lunghi",
  crossesAttempted: "Cross tentati",
  crossesAccuracy: "Precisione dei cross",
  dribblesAttempted: "Dribbling tentati",
  dribblesSuccess: "Dribbling riusciti",
  finalThirdEntries: "Ingressi in ultimo terzo",
  finalThirdPhaseAttempted: "Azioni in ultimo terzo",
  finalThirdPhaseSuccess: "Efficacia in ultimo terzo",
  throughBalls: "Passaggi filtranti",
  dispossessed: "Palloni persi in contrasto",
  attacks: "Attacchi",
  attackShare: "Quota di attacchi",
  dangerousAttacks: "Attacchi pericolosi",
  dangerousAttackShare: "Quota di attacchi pericolosi",
  ballSafe: "Possesso in sicurezza",
  ballSafeShare: "Quota di possesso in sicurezza",

  tackles: "Contrasti",
  tacklesWonShare: "Quota di contrasti vinti",
  interceptions: "Intercetti",
  clearances: "Respinte difensive",
  recoveries: "Palloni recuperati",
  duels: "Duelli",
  groundDuelsContested: "Duelli a terra",
  groundDuelsWon: "Duelli a terra vinti",
  aerialDuelsContested: "Duelli aerei",
  aerialDuelsWon: "Duelli aerei vinti",
  errorsLeadToAShot: "Errori che concedono un tiro",

  totalSaves: "Interventi del portiere",
  bigSaves: "Parate decisive",
  goalsPrevented: "Gol evitati",
  punches: "Respinte di pugno",
  highClaims: "Uscite alte",

  redCards: "Cartellini rossi",
  freeKicks: "Punizioni",
  fouledInFinalThird: "Falli subiti in ultimo terzo",
  throwIns: "Rimesse laterali",
  goalKicks: "Rinvii dal fondo",
};

export const SQUAD_POSITION_LABELS: Readonly<Record<SquadPosition, string>> = {
  goalkeeper: "Portieri",
  defender: "Difensori",
  midfielder: "Centrocampisti",
  forward: "Attaccanti",
};

export const PLAYER_METRIC_LABELS: Readonly<Partial<Record<PlayerMetricKey, string>>> = {
  saves: "Parate",
  goalsConceded: "Gol subiti",
  goalsPrevented: "Gol evitati",
  savedShotsFromInsideTheBox: "Parate da dentro l'area",
  highClaims: "Uscite alte",
  punches: "Respinte di pugno",
  totalClearance: "Respinte",
  interception: "Intercetti",
  totalTackle: "Contrasti",
  wonTackle: "Contrasti vinti",
  aerialWon: "Duelli aerei vinti",
  blockedScoringAttempt: "Tiri murati",
  errorLeadToAShot: "Errori che concedono un tiro",
  accuratePass: "Passaggi riusciti",
  keyPass: "Passaggi chiave",
  totalProgression: "Progressioni",
  ballRecovery: "Palloni recuperati",
  duelWon: "Duelli vinti",
  expectedAssists: "Assist attesi (xA)",
  possessionLost: "Palloni persi",
  goals: "Gol",
  expectedGoals: "Gol attesi (xG)",
  goalAssist: "Assist",
  totalShots: "Tiri",
  shotsOnTarget: "Tiri in porta",
  bigChanceMissed: "Grandi occasioni fallite",
};
